import setuptools

setup_reqs = ["setuptools_scm"]
install_reqs = ["pyserial"]
test_reqs = ["pytest", "pytest-flake8", "pytest-cov", "pytest-mock"]
dev_reqs = setup_reqs+install_reqs+test_reqs+["documenteer[pipelines]"]
scm_version_template = """# Generated by setuptools_scm
__all__ = ["__version__"]

__version__ = "{version}"
"""

setuptools.setup(
    name="ts_tunablelaser",
    use_scm_version={
        "write_to": "python/lsst/ts/tunablelaser/version.py",
        "write_to_template": scm_version_template
    },
    setup_requires=setup_reqs,
    install_requires=install_reqs,
    package_dir={"": "python"},
    packages=setuptools.find_namespace_packages(where="python"),
    extras_require={'dev': dev_reqs}
)
