# Auto-generated by generate_canbus_from_csv.
# Source CSV: REMOTECONTROL (1).CSV
# Device: PGD217 NT252
# ruff: noqa

"""Auto-generated canbus definitions for the vendor device 'PGD217 NT252'."""

__all__ = [
    "MCPU800",
    "PH532",
    "MidiOPG",
    "LDCO48BP",
    "TK6",
    "CPU8000",
    "MLDCO48",
    "HV40W",
    "FOPO",
    "SOPO",
    "SH1",
    "C1",
]
from lsst.ts.tunablelaser import interfaces
from lsst.ts.tunablelaser.register import AsciiRegister


class MCPU800(interfaces.CanbusModule):
    """Auto-generated canbus register container for the vendor module 'M_CPU800'."""

    def __init__(self):
        super().__init__()
        self.name = "M_CPU800"
        self.id_0x12 = 0x12
        self.id_0x11 = 0x11
        self.power_id_0x12_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x12,
            register_name="Power",
            read_only=False,
            accepted_values=["OFF", "ON"],
        )
        self.diode_current_on_id_0x12_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x12,
            register_name="Diode current ON",
            read_only=False,
            accepted_values=["OFF", "ON"],
        )
        self.output_energy_level_id_0x12_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x12,
            register_name="Output Energy level",
            read_only=False,
            accepted_values=["OFF", "Adjust", "MAX"],
        )
        self.continuous_burst_mode_trigger_burst_id_0x12_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x12,
            register_name="Continuous %2f Burst mode %2f Trigger burst",
            read_only=False,
            accepted_values=["Continuous", "Burst", "Trigger"],
        )
        self.qsw_adjustment_output_delay_id_0x12_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x12,
            register_name="QSW Adjustment output delay",
            read_only=False,
            accepted_values=range(50, 1001),
        )
        self.frequency_divider_id_0x12_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x12,
            register_name="Frequency divider",
            read_only=False,
            accepted_values=range(1, 5001),
        )
        self.burst_length_id_0x12_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x12,
            register_name="Burst length",
            read_only=False,
            accepted_values=range(1, 50001),
        )
        self.synchronization_mode_id_0x12_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x12,
            register_name="Synchronization mode",
            read_only=False,
            accepted_values=["Internal", "External"],
        )
        self.repetition_rate_id_0x12_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x12,
            register_name="Repetition rate",
            read_only=False,
            accepted_values=range(1, 11001),
        )
        self.external_interlock_state_id_0x12_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x12,
            register_name="External interlock state",
        )
        self.power_id_0x11_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x11,
            register_name="Power",
            read_only=False,
            accepted_values=["OFF", "ON"],
        )
        self.display_current_id_0x11_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x11,
            register_name="Display Current",
        )


class PH532(interfaces.CanbusModule):
    """Auto-generated canbus register container for the vendor module 'PH_532'."""

    def __init__(self):
        super().__init__()
        self.name = "PH_532"
        self.id = 0x37
        self.power_id_0x37_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id,
            register_name="Power",
        )


class MidiOPG(interfaces.CanbusModule):
    """Auto-generated canbus register container for the vendor module 'MidiOPG'."""

    def __init__(self):
        super().__init__()
        self.name = "MidiOPG"
        self.id = 0x1F
        self.wavelength_id_0x1f_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id,
            register_name="WaveLength",
            read_only=False,
            accepted_values=range(1, 2601),
        )
        self.status_id_0x1f_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id,
            register_name="Status",
        )


class LDCO48BP(interfaces.CanbusModule):
    """Auto-generated canbus register container for the vendor module 'LDCO48BP'."""

    def __init__(self):
        super().__init__()
        self.name = "LDCO48BP"
        self.id_0x30 = 0x30
        self.id_0x32 = 0x32
        self.id_0x1c = 0x1C
        self.id_0x1d = 0x1D
        self.set_temperature_id_0x30_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x30,
            register_name="Set temperature",
            read_only=False,
            accepted_values=range(-200, 4601),
        )
        self.set_temperature_id_0x32_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x32,
            register_name="Set temperature",
            read_only=False,
            accepted_values=range(-200, 4601),
        )
        self.display_temperature_id_0x32_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x32,
            register_name="Display temperature",
        )
        self.display_temperature_id_0x30_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x30,
            register_name="Display temperature",
        )
        self.error_code_id_0x1c_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x1c,
            register_name="Error Code",
        )
        self.error_code_id_0x1d_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x1d,
            register_name="Error Code",
        )


class TK6(interfaces.CanbusModule):
    """Auto-generated canbus register container for the vendor module 'TK6'."""

    def __init__(self):
        super().__init__()
        self.name = "TK6"
        self.id = 0x2C
        self.set_temperature_id_0x2c_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id,
            register_name="Set temperature",
            read_only=False,
            accepted_values=range(-2300, 26601),
        )
        self.display_temperature_id_0x2c_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id,
            register_name="Display temperature",
        )


class CPU8000(interfaces.CanbusModule):
    """Auto-generated canbus register container for the vendor module 'CPU8000'."""

    def __init__(self):
        super().__init__()
        self.name = "CPU8000"
        self.id = 0x10
        self.power_id_0x10_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id,
            register_name="Power",
            read_only=False,
            accepted_values=["OFF", "ON"],
        )
        self.display_current_id_0x10_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id,
            register_name="Display Current",
        )


class MLDCO48(interfaces.CanbusModule):
    """Auto-generated canbus register container for the vendor module 'M_LDCO48'."""

    def __init__(self):
        super().__init__()
        self.name = "M_LDCO48"
        self.id_0x21 = 0x21
        self.id_0x22 = 0x22
        self.error_code_id_0x21_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x21,
            register_name="Error Code",
        )
        self.error_code_id_0x22_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id_0x22,
            register_name="Error Code",
        )


class HV40W(interfaces.CanbusModule):
    """Auto-generated canbus register container for the vendor module 'HV40W'."""

    def __init__(self):
        super().__init__()
        self.name = "HV40W"
        self.id = 0x28
        self.error_code_id_0x28_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id,
            register_name="Error Code",
        )


class FOPO(interfaces.CanbusModule):
    """Auto-generated canbus register container for the vendor module 'FOPO'."""

    def __init__(self):
        super().__init__()
        self.name = "FOPO"
        self.id = 0x33
        self.error_code_id_0x33_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id,
            register_name="Error Code",
        )


class SOPO(interfaces.CanbusModule):
    """Auto-generated canbus register container for the vendor module 'SOPO'."""

    def __init__(self):
        super().__init__()
        self.name = "SOPO"
        self.id = 0x34
        self.error_code_id_0x34_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id,
            register_name="Error Code",
        )


class SH1(interfaces.CanbusModule):
    """Auto-generated canbus register container for the vendor module 'SH1'."""

    def __init__(self):
        super().__init__()
        self.name = "SH1"
        self.id = 0x35
        self.error_code_id_0x35_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id,
            register_name="Error Code",
        )


class C1(interfaces.CanbusModule):
    """Auto-generated canbus register container for the vendor module 'C1'."""

    def __init__(self):
        super().__init__()
        self.name = "C1"
        self.id = 0x36
        self.error_code_id_0x36_register = AsciiRegister(
            module_name=self.name,
            module_id=self.id,
            register_name="Error Code",
        )
